"""v13_community_tables

Revision ID: b5417e864e9c
Revises: 
Create Date: 2026-03-15 10:27:59.592217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5417e864e9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_credit_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('shared_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=False),
    sa.Column('problem_desc', sa.Text(), nullable=False),
    sa.Column('solution_desc', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tool_versions', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('share_score', sa.Float(), nullable=False),
    sa.Column('fix_pattern', sa.String(length=50), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('upvote_count', sa.Integer(), nullable=False),
    sa.Column('downvote_count', sa.Integer(), nullable=False),
    sa.Column('adoption_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_experiences', schema=None) as batch_op:
        batch_op.create_index('idx_exp_platform_framework', ['platform', 'framework'], unique=False)
        batch_op.create_index('idx_exp_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_experiences_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_experiences_framework'), ['framework'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_experiences_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_experiences_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_experiences_user_id'), ['user_id'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_type', sa.String(length=50), nullable=False),
    sa.Column('badge_name', sa.String(length=100), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index('idx_badge_user_type', ['user_id', 'badge_type'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=False),
    sa.Column('bio', sa.String(length=200), nullable=False),
    sa.Column('expertise_tags', sa.JSON(), nullable=True),
    sa.Column('stats_cache', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('experience_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['shared_experiences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experience_votes', schema=None) as batch_op:
        batch_op.create_index('idx_vote_unique', ['experience_id', 'user_id', 'vote_type'], unique=True)

    op.create_table('debug_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_stack', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('fix_description', sa.Text(), nullable=False),
    sa.Column('fix_files', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('shared_experience_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['shared_experience_id'], ['shared_experiences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debug_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snapshot_user_resolved', ['user_id', 'resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_debug_snapshots_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('credits_used', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('plan')
        batch_op.drop_column('credits_used')
        batch_op.drop_column('credits')

    with op.batch_alter_table('debug_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debug_snapshots_user_id'))
        batch_op.drop_index('idx_snapshot_user_resolved')

    op.drop_table('debug_snapshots')
    with op.batch_alter_table('experience_votes', schema=None) as batch_op:
        batch_op.drop_index('idx_vote_unique')

    op.drop_table('experience_votes')
    op.drop_table('user_profiles')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index('idx_badge_user_type')

    op.drop_table('user_badges')
    with op.batch_alter_table('shared_experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_experiences_user_id'))
        batch_op.drop_index(batch_op.f('ix_shared_experiences_status'))
        batch_op.drop_index(batch_op.f('ix_shared_experiences_platform'))
        batch_op.drop_index(batch_op.f('ix_shared_experiences_framework'))
        batch_op.drop_index(batch_op.f('ix_shared_experiences_error_type'))
        batch_op.drop_index('idx_exp_status_created')
        batch_op.drop_index('idx_exp_platform_framework')

    op.drop_table('shared_experiences')
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transactions_user_id'))
        batch_op.drop_index('idx_credit_user_created')

    op.drop_table('credit_transactions')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
